apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: proshop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: prod/proshop/mongodba
        property: MONGO_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/proshop/mongodba
        property: JWT_SECRET
